version: "3"

services:
  whispernote:
    build: .
    container_name: whispernote
    ports:
      - "4000:3000"
    restart: always
  loki:
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"

  promtail:
   image: grafana/promtail:latest
   volumes:
     - ./promtail-config.yaml:/etc/promtail/promtail-config.yaml
     - /var/log/whispernote:/var/log/whispernote
   command: -config.file=/etc/promtail/promtail-config.yaml



  
